/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyForm {
        "age": number;
        "busy": boolean;
        "carBodyStyle": string;
        "color": string;
        "counter": number;
        "email": string;
        "favoriteCar": string;
        "fullName": string;
        "hoodScoop": boolean;
        "login": boolean;
        "specialInstructions": string;
        "userName": string;
        "vegetarian": boolean;
        "volume": any;
    }
    interface MySelect {
        "name": string;
        "required": boolean;
    }
}
declare global {
    interface HTMLMyFormElement extends Components.MyForm, HTMLStencilElement {
    }
    var HTMLMyFormElement: {
        prototype: HTMLMyFormElement;
        new (): HTMLMyFormElement;
    };
    interface HTMLMySelectElement extends Components.MySelect, HTMLStencilElement {
    }
    var HTMLMySelectElement: {
        prototype: HTMLMySelectElement;
        new (): HTMLMySelectElement;
    };
    interface HTMLElementTagNameMap {
        "my-form": HTMLMyFormElement;
        "my-select": HTMLMySelectElement;
    }
}
declare namespace LocalJSX {
    interface MyForm {
        "age"?: number;
        "busy"?: boolean;
        "carBodyStyle"?: string;
        "color"?: string;
        "counter"?: number;
        "email"?: string;
        "favoriteCar"?: string;
        "fullName"?: string;
        "hoodScoop"?: boolean;
        "login"?: boolean;
        "specialInstructions"?: string;
        "userName"?: string;
        "vegetarian"?: boolean;
        "volume"?: any;
    }
    interface MySelect {
        "name"?: string;
        "required"?: boolean;
    }
    interface IntrinsicElements {
        "my-form": MyForm;
        "my-select": MySelect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-form": LocalJSX.MyForm & JSXBase.HTMLAttributes<HTMLMyFormElement>;
            "my-select": LocalJSX.MySelect & JSXBase.HTMLAttributes<HTMLMySelectElement>;
        }
    }
}
